const cardImg = [
    "1_spades.png",
    "2_spades.png",
    "3_spades.png",
    "4_spades.png",
    "5_spades.png",
    "6_spades.png",
    "7_spades.png",
    "8_spades.png",
    "9_spades.png",
    "10_spades.png",
    "11_spades.png",
    "12_spades.png",
    "13_spades.png",
]